# Generated by Django 4.0.6 on 2022-12-07 05:09

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('logo', models.ImageField(upload_to='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentOpenings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=128)),
                ('hiring_city', models.CharField(max_length=128)),
                ('hiring_state', models.CharField(max_length=128)),
                ('hiring_country', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=128)),
                ('salary_range_from', models.IntegerField()),
                ('salary_range_to', models.IntegerField()),
                ('job_role', models.CharField(max_length=128)),
                ('domain', models.CharField(max_length=128)),
                ('job_description', django_quill.fields.QuillField()),
                ('experience_from_years', models.SmallIntegerField()),
                ('experience_to_years', models.SmallIntegerField()),
                ('permanent', models.BooleanField(default=True)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('online', models.BooleanField(default=True)),
                ('full_time_job', models.BooleanField(default=True)),
                ('job_country', models.CharField(max_length=128)),
                ('industries', models.CharField(max_length=128)),
                ('job_description_file', models.FileField(upload_to='JD/')),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.EmailField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WalkInForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('full_name', models.CharField(max_length=128)),
                ('position_applied', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=128)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=128)),
                ('mobile_number', models.CharField(max_length=13)),
                ('current_location', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('highest_qualification', models.CharField(max_length=128)),
                ('resume', models.FileField(upload_to='resume/')),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.currentopenings')),
            ],
        ),
    ]
