# Generated by Django 4.0.6 on 2022-12-07 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0001_initial'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkinform',
            name='opening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openings.openings'),
        ),
        migrations.DeleteModel(
            name='CurrentOpenings',
        ),
    ]
