# Generated by Django 4.0.6 on 2022-12-07 16:41

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Openings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=128)),
                ('hiring_city', models.CharField(max_length=128)),
                ('hiring_state', models.CharField(max_length=128)),
                ('hiring_country', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=128)),
                ('salary_range_from', models.IntegerField()),
                ('salary_range_to', models.IntegerField()),
                ('job_role', models.CharField(max_length=128)),
                ('domain', models.CharField(max_length=128)),
                ('job_description', django_quill.fields.QuillField()),
                ('experience_from_years', models.SmallIntegerField()),
                ('experience_to_years', models.SmallIntegerField()),
                ('permanent', models.BooleanField(default=True)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('online', models.BooleanField(default=True)),
                ('full_time_job', models.BooleanField(default=True)),
                ('job_country', models.CharField(max_length=128)),
                ('industries', models.CharField(max_length=128)),
                ('job_description_file', models.FileField(upload_to='JD/')),
                ('display', models.BooleanField(default=True)),
            ],
        ),
    ]
